devices:
  10.0.0.40:
    name: Desk Light
    transition: 500
    model: lamp4
  10.0.0.41:
    name: TV Lamp
    transition: 500
    model: bslamp2
custom_effects:
  - name: Fire Flicker
    flow_params:
      count: 0
      transitions:
        - TemperatureTransition: [1900, 1000, 80]
        - TemperatureTransition: [1900, 2000, 60]
        - SleepTransition:       [1000]
